/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

export default [
  [
    {
      log_id: 1,
      log_date: "2025-01-01",
      completed: true,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 2,
      log_date: "2025-01-02",
      completed: false,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 3,
      log_date: "2025-01-03",
      completed: false,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 4,
      log_date: "2025-01-04",
      completed: true,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 5,
      log_date: "2025-01-05",
      completed: true,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 6,
      log_date: "2025-01-06",
      completed: true,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 7,
      log_date: "2025-01-07",
      completed: false,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 8,
      log_date: "2025-01-08",
      completed: false,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 9,
      log_date: "2025-01-09",
      completed: true,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 10,
      log_date: "2025-01-10",
      completed: true,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 11,
      log_date: "2025-01-11",
      completed: false,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 12,
      log_date: "2025-01-12",
      completed: true,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 13,
      log_date: "2025-01-13",
      completed: false,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 14,
      log_date: "2025-01-14",
      completed: true,
      habit_id: 1,
      log_month: "January",
    },
    {
      log_id: 15,
      log_date: "2025-01-15",
      completed: false,
      habit_id: 1,
      log_month: "January",
    },

    {
      log_id: 16,
      log_date: "2025-01-01",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 17,
      log_date: "2025-01-02",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 18,
      log_date: "2025-01-03",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 19,
      log_date: "2025-01-04",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 20,
      log_date: "2025-01-05",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 21,
      log_date: "2025-01-06",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 22,
      log_date: "2025-01-07",
      completed: false,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 23,
      log_date: "2025-01-08",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 24,
      log_date: "2025-01-09",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 25,
      log_date: "2025-01-10",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 26,
      log_date: "2025-01-11",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 27,
      log_date: "2025-01-12",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 28,
      log_date: "2025-01-13",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 29,
      log_date: "2025-01-14",
      completed: false,
      habit_id: 2,
      log_month: "January",
    },
    {
      log_id: 30,
      log_date: "2025-01-15",
      completed: true,
      habit_id: 2,
      log_month: "January",
    },

    {
      log_id: 31,
      log_date: "2025-01-01",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 32,
      log_date: "2025-01-02",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 33,
      log_date: "2025-01-03",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 34,
      log_date: "2025-01-04",
      completed: false,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 35,
      log_date: "2025-01-05",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 36,
      log_date: "2025-01-06",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 37,
      log_date: "2025-01-07",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 38,
      log_date: "2025-01-08",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 39,
      log_date: "2025-01-09",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 40,
      log_date: "2025-01-10",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 41,
      log_date: "2025-01-11",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 42,
      log_date: "2025-01-12",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 43,
      log_date: "2025-01-13",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 44,
      log_date: "2025-01-14",
      completed: true,
      habit_id: 3,
      log_month: "January",
    },
    {
      log_id: 45,
      log_date: "2025-01-15",
      completed: false,
      habit_id: 3,
      log_month: "January",
    },

    {
      log_id: 46,
      log_date: "2025-01-01",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 47,
      log_date: "2025-01-02",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 48,
      log_date: "2025-01-03",
      completed: false,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 49,
      log_date: "2025-01-04",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 50,
      log_date: "2025-01-05",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 51,
      log_date: "2025-01-06",
      completed: false,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 52,
      log_date: "2025-01-07",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 53,
      log_date: "2025-01-08",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 54,
      log_date: "2025-01-09",
      completed: false,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 55,
      log_date: "2025-01-10",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 56,
      log_date: "2025-01-11",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 57,
      log_date: "2025-01-12",
      completed: false,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 58,
      log_date: "2025-01-13",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 59,
      log_date: "2025-01-14",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },
    {
      log_id: 60,
      log_date: "2025-01-15",
      completed: true,
      habit_id: 4,
      log_month: "January",
    },

    {
      log_id: 61,
      log_date: "2025-01-01",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 62,
      log_date: "2025-01-02",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 63,
      log_date: "2025-01-03",
      completed: false,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 64,
      log_date: "2025-01-04",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 65,
      log_date: "2025-01-05",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 66,
      log_date: "2025-01-06",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 67,
      log_date: "2025-01-07",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 68,
      log_date: "2025-01-08",
      completed: false,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 69,
      log_date: "2025-01-09",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 70,
      log_date: "2025-01-10",
      completed: false,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 71,
      log_date: "2025-01-11",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 72,
      log_date: "2025-01-12",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 73,
      log_date: "2025-01-13",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 74,
      log_date: "2025-01-14",
      completed: false,
      habit_id: 5,
      log_month: "January",
    },
    {
      log_id: 75,
      log_date: "2025-01-15",
      completed: true,
      habit_id: 5,
      log_month: "January",
    },

    {
      log_id: 76,
      log_date: "2025-01-01",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 77,
      log_date: "2025-01-02",
      completed: false,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 78,
      log_date: "2025-01-03",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 79,
      log_date: "2025-01-04",
      completed: false,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 80,
      log_date: "2025-01-05",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 81,
      log_date: "2025-01-06",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 82,
      log_date: "2025-01-07",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 83,
      log_date: "2025-01-08",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 84,
      log_date: "2025-01-09",
      completed: false,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 85,
      log_date: "2025-01-10",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 86,
      log_date: "2025-01-11",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 87,
      log_date: "2025-01-12",
      completed: false,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 88,
      log_date: "2025-01-13",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 89,
      log_date: "2025-01-14",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },
    {
      log_id: 90,
      log_date: "2025-01-15",
      completed: true,
      habit_id: 6,
      log_month: "January",
    },

    {
      log_id: 91,
      log_date: "2025-01-01",
      completed: true,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 92,
      log_date: "2025-01-02",
      completed: false,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 93,
      log_date: "2025-01-03",
      completed: true,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 94,
      log_date: "2025-01-04",
      completed: false,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 95,
      log_date: "2025-01-05",
      completed: true,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 96,
      log_date: "2025-01-06",
      completed: true,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 97,
      log_date: "2025-01-07",
      completed: false,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 98,
      log_date: "2025-01-08",
      completed: true,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 99,
      log_date: "2025-01-09",
      completed: true,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 100,
      log_date: "2025-01-10",
      completed: false,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 101,
      log_date: "2025-01-11",
      completed: true,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 102,
      log_date: "2025-01-12",
      completed: false,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 103,
      log_date: "2025-01-13",
      completed: true,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 104,
      log_date: "2025-01-14",
      completed: true,
      habit_id: 7,
      log_month: "January",
    },
    {
      log_id: 105,
      log_date: "2025-01-15",
      completed: true,
      habit_id: 7,
      log_month: "January",
    },

    {
      log_id: 106,
      log_date: "2025-01-01",
      completed: false,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 107,
      log_date: "2025-01-02",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 108,
      log_date: "2025-01-03",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 109,
      log_date: "2025-01-04",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 110,
      log_date: "2025-01-05",
      completed: false,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 111,
      log_date: "2025-01-06",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 112,
      log_date: "2025-01-07",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 113,
      log_date: "2025-01-08",
      completed: false,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 114,
      log_date: "2025-01-09",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 115,
      log_date: "2025-01-10",
      completed: false,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 116,
      log_date: "2025-01-11",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 117,
      log_date: "2025-01-12",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 118,
      log_date: "2025-01-13",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 119,
      log_date: "2025-01-14",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },
    {
      log_id: 120,
      log_date: "2025-01-15",
      completed: true,
      habit_id: 8,
      log_month: "January",
    },

    {
      log_id: 121,
      log_date: "2025-01-01",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 122,
      log_date: "2025-01-02",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 123,
      log_date: "2025-01-03",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 124,
      log_date: "2025-01-04",
      completed: false,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 125,
      log_date: "2025-01-05",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 126,
      log_date: "2025-01-06",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 127,
      log_date: "2025-01-07",
      completed: false,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 128,
      log_date: "2025-01-08",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 129,
      log_date: "2025-01-09",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 130,
      log_date: "2025-01-10",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 131,
      log_date: "2025-01-11",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 132,
      log_date: "2025-01-12",
      completed: false,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 133,
      log_date: "2025-01-13",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 134,
      log_date: "2025-01-14",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },
    {
      log_id: 135,
      log_date: "2025-01-15",
      completed: true,
      habit_id: 9,
      log_month: "January",
    },

    {
      log_id: 136,
      log_date: "2025-01-01",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 137,
      log_date: "2025-01-02",
      completed: false,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 138,
      log_date: "2025-01-03",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 139,
      log_date: "2025-01-04",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 140,
      log_date: "2025-01-05",
      completed: false,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 141,
      log_date: "2025-01-06",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 142,
      log_date: "2025-01-07",
      completed: false,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 143,
      log_date: "2025-01-08",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 144,
      log_date: "2025-01-09",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 145,
      log_date: "2025-01-10",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 146,
      log_date: "2025-01-11",
      completed: false,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 147,
      log_date: "2025-01-12",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 148,
      log_date: "2025-01-13",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 149,
      log_date: "2025-01-14",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
    {
      log_id: 150,
      log_date: "2025-01-15",
      completed: true,
      habit_id: 10,
      log_month: "January",
    },
  ],
];
